version: 2.0
jobs:
  gcc:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # GCC-8
      - run:
          name: GCC-8 build + MPI
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DPARTIO_ROOT=/home/cbgeo/partio/ -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
            make -j4
            ctest -VV
  clang:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # Clang-6.0
      - run:
          name: Clang-6.0 + Static analysis
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            scan-build cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DPARTIO_ROOT=/home/cbgeo/partio/ -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
            scan-build make -j4 
            ctest -VV
  cppcheck:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      - run:
          name: cppcheck
          command: |
            cppcheck --version
            cppcheck --enable=warning --inconclusive --force --language=c++ --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1
      # clang-format
      - run:
          name: clang-format
          command: |
            python ./clang-tools/run-clang-format.py -r include/* src/* tests/*
  codecov:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # codecoverage
      - run:
          name: codecov.io
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DCMAKE_CXX_COMPILER=g++ -DPARTIO_ROOT=/home/cbgeo/partio/ -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DENABLE_COVERAGE=On ..
            make mpmviz-test_coverage -j4
            ./mpmviz-test_coverage
            make gcov
            make lcov
            bash <(curl -s https://codecov.io/bash) -X gcov
workflows:
    version: 2
    build:
        jobs:
            - gcc
            - clang
            - cppcheck
            - codecov